amqp_url = "amqps://fedora:@rabbitmq.fedoraproject.org/%2Fpublic_pubsub"
passive_declares = true

[tls]
ca_cert = "/etc/fedora-messaging/cacert.pem"
keyfile = "/etc/fedora-messaging/fedora-key.pem"
certfile = "/etc/fedora-messaging/fedora-cert.pem"

[client_properties]
app = "Flatpak Status"
app_url = "https://github.com/owtaylor/flatpak-status"

[qos]
prefetch_size = 0
prefetch_count = 25
